(function() {var implementors = {};
implementors["log"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='log/enum.LogLevel.html' title='log::LogLevel'>LogLevel</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='log/enum.LogLevelFilter.html' title='log::LogLevelFilter'>LogLevelFilter</a>",];implementors["libc"] = [];implementors["syntex_syntax"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/util/interner/struct.RcStr.html' title='syntex_syntax::util::interner::RcStr'>RcStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/ast/struct.Name.html' title='syntex_syntax::ast::Name'>Name</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='syntex_syntax/feature_gate/enum.GatedCfgAttr.html' title='syntex_syntax::feature_gate::GatedCfgAttr'>GatedCfgAttr</a>","impl&lt;T: <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/owned_slice/struct.OwnedSlice.html' title='syntex_syntax::owned_slice::OwnedSlice'>OwnedSlice</a>&lt;T&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/parse/parser/struct.Restrictions.html' title='syntex_syntax::parse::parser::Restrictions'>Restrictions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/parse/token/struct.InternedString.html' title='syntex_syntax::parse::token::InternedString'>InternedString</a>",];implementors["bindgen"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='bindgen/enum.LinkType.html' title='bindgen::LinkType'>LinkType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
